import fs from 'node:fs/promises';
import path from 'node:path';

const root=path.dirname(new URL(import.meta.url).pathname.replace(/^\/(.:)/,'$1'));
const read=p=>fs.readFile(path.join(root,p),'utf8');
const b64=async p=>(await fs.readFile(path.join(root,p))).toString('base64');
const data=async(p,mime)=>`data:${mime};base64,${await b64(p)}`;
const [baseCss,enhanceCss,dutyCss,standaloneCss0,standaloneUi,exportsJs,apiJs,dutyJs,appJs,seedText,jszip,pdfLib,logo,favicon,eutm,fontRegular,fontBold,weekTemplate,rulesTemplate,manual0]=await Promise.all([
  read('src/reference-styles.css'),read('src/reference-enhancements.css'),read('src/reference-duty-list.css'),read('src/standalone.css'),read('src/standalone-ui.js'),read('src/exports.js'),read('src/standalone-api.js'),read('src/duty-list.js'),read('src/app.js'),read('src/seed.json'),
  fs.readFile('C:/Users/fonse/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/jszip/dist/jszip.min.js','utf8'),
  fs.readFile('C:/Users/fonse/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/pdf-lib/dist/pdf-lib.min.js','utf8'),
  data('assets/logo_dlh.png','image/png'),data('assets/logo_dlh.png','image/png'),data('assets/logo_eutm.png','image/png'),data('assets/LiberationSans-Regular.ttf','font/ttf'),data('assets/LiberationSans-Bold.ttf','font/ttf'),b64('templates/duty_list_template.docx'),b64('templates/duty_rules_template.docx'),read('src/manual.html')
]);
const flagFiles=await fs.readdir(path.join(root,'assets/flags'));const flags={};for(const name of flagFiles){if(!name.toLowerCase().endsWith('.png'))continue;flags[path.basename(name,'.png').toUpperCase()]=await data(`assets/flags/${name}`,'image/png')}
const standaloneCss=standaloneCss0.replace('__FONT_REGULAR__',fontRegular).replace('__FONT_BOLD__',fontBold);
const manual=manual0.replaceAll('/assets/logo_dlh.png',logo).replaceAll('<link rel="icon" type="image/png" href="'+logo+'">','');
const icons={home:'<path d="m3 11 9-8 9 8v10h-6v-6H9v6H3z"/>',people:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M22 21v-2a4 4 0 0 0-3-3.8"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M8 3v4M16 3v4M3 10h18"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M19 15l2 2-4 4-2-2M9 5 7 3 3 7l2 2M12 2v3M12 19v3M2 12h3M19 12h3"/>',help:'<circle cx="12" cy="12" r="10"/><path d="M9.2 9a3 3 0 1 1 4.7 2.5c-1 .7-1.9 1.2-1.9 2.5M12 18h.01"/>'};
const ico=n=>`<svg viewBox="0 0 24 24">${icons[n]}</svg>`;
const bootstrap=`window.DLH_SEED=${seedText};window.DLH_FLAGS=${JSON.stringify(flags)};window.DLH_WEEK_TEMPLATE_B64='${weekTemplate}';window.DLH_RULES_TEMPLATE_B64='${rulesTemplate}';window.DLH_MANUAL_HTML=${JSON.stringify(manual)};`;
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#071b36"><title>Duty List Helper</title><link rel="icon" href="${favicon}"><style>${baseCss}\n${enhanceCss}\n${dutyCss}\n${standaloneCss}</style></head><body><div class="app"><aside><div class="brand"><img src="${logo}" alt="DLH"><div><b>Duty List</b><span>HELPER</span></div></div><nav><small>OVERVIEW</small><button class="nav active" data-page="dashboard"><i>${ico('home')}</i>Dashboard</button><small>WORKFORCE</small><button class="nav" data-page="people"><i>${ico('people')}</i>Personnel</button><button class="nav" data-page="exemptions"><i>${ico('clock')}</i>Duty Exemptions</button><button class="nav" data-page="duty-list"><i>${ico('calendar')}</i>Duty List</button><small>CONFIGURATION</small><button class="nav" data-page="days-off"><i>${ico('calendar')}</i>Days Off Manager</button><button class="nav" data-page="settings"><i>${ico('settings')}</i>Lists &amp; Settings</button><small>HELP</small><button class="nav help-link" onclick="openManual()"><i>${ico('help')}</i>User Manual</button></nav><div class="side-foot version-foot"><span>DLH v1.0 @ dev by OR-9 FONSECA, Filipe,</span><strong>EUTM RCA | PRT Army | 2026</strong></div></aside><main><header><div><button id="menu">☰</button><span class="eyebrow">EUTM RCA · DUTY MANAGEMENT</span><h1 id="title">Dashboard</h1></div><div class="top-tools"><button id="admin-lock" class="admin-lock" onclick="toggleAdminLock()">○ Protected</button><div class="today"><span>Today</span><b id="today"></b></div></div></header><section id="content"></section></main></div><div id="modal" class="modal"></div><div id="toast"></div><script>${jszip}</script><script>${pdfLib}</script><script>${bootstrap}</script><script>${standaloneUi}</script><script>${exportsJs}</script><script>${apiJs}</script><script>${dutyJs}</script><script>${appJs}</script></body></html>`;
await fs.mkdir(path.join(root,'application'),{recursive:true});
await fs.writeFile(path.join(root,'application','Duty List Helper.html'),html,'utf8');
console.log(path.join(root,'application','Duty List Helper.html'));
