import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
import path from 'node:path';

const require=createRequire(import.meta.url);
const { chromium }=require('C:/Users/fonse/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',args:['--allow-file-access-from-files']});
const page=await browser.newPage({viewport:{width:1600,height:920}});
const errors=[];
page.on('pageerror',error=>errors.push(error.message));
await page.goto(pathToFileURL(path.resolve('application/Duty List Helper.html')).href,{waitUntil:'load'});
await page.waitForSelector('.dashboard-command',{timeout:30000});
await page.screenshot({path:'tmp/dashboard.png',fullPage:true});
const result=await page.evaluate(async()=>{
  sessionStorage.setItem('dlh.admin.unlocked','1');updateLock();
  const settingsResponse=await fetch('/api/settings',{method:'PUT',body:JSON.stringify({duty_list_mode:'weekend_lists'})});
  await load();setPage('settings');
  const modeOptions=[...document.querySelectorAll('select[name="duty_list_mode"] option')].map(x=>({value:x.value,text:x.textContent}));
  setPage('exemptions');exemptionForm();
  const exemptionOptions=[...document.querySelectorAll('select[name="person_id"] option')].slice(0,4).map(x=>x.textContent);
  closeModal();setPage('duty-list');
  const weekly=await DLH_EXPORTS.week({week_start:'2026-09-07',document_number:'NUMBER'},state);
  const calendar=await DLH_EXPORTS.calendar('2026-09-01',state);
  const rules=await DLH_EXPORTS.rules(state),rulesZip=await JSZip.loadAsync(rules.bytes),rulesXml=await rulesZip.file('word/document.xml').async('string');
  const ordered=state.people.every((person,index)=>!index||compareDutySeniority({person:state.people[index-1]},{person})<=0);
  return {settingsStatus:settingsResponse.status,mode:state.settings.duty_list_mode,modeOptions,exemptionOptions,ordered,saturdayRotation:dutyChangeRotation('2026-09-26'),mondayRotation:dutyChangeRotation('2026-09-28'),rulesMode:rulesXml.includes('Weekdays and Weekends / Day Off'),rulesSaturday:rulesXml.includes('Saturdays, Sundays or official days off'),rulesRank:rulesXml.includes('highest rank, then the earliest date of rank'),people:state.people.length,assignments:state.duty_assignments.length,weeklyName:weekly.name,weeklyBytes:weekly.bytes.length,pdfName:calendar.name,pdfBytes:calendar.bytes.length,logo:document.querySelector('.brand img').naturalWidth,calendarCells:document.querySelectorAll('.duty-table tbody .duty-day').length};
});
await page.screenshot({path:'tmp/duty-list.png',fullPage:true});
console.log(JSON.stringify({errors,result},null,2));
await browser.close();
