let state={}, page='dashboard', showAllPersonnel=false; const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api=async(url,opt={})=>{if(opt.body){opt.headers={'Content-Type':'application/json'};opt.body=JSON.stringify(opt.body)}let r=await fetch(url,opt),d=await r.json();if(!r.ok)throw Error(d.error||'Something went wrong');return d};
async function load(){state=await api('/api/bootstrap');render()};
function toast(x){let t=$('#toast');t.textContent=x;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function setPage(p){page=p;if(p!=='people')showAllPersonnel=false;document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===p));$('#title').textContent={dashboard:'Dashboard',people:'Personnel',exemptions:'Duty Exemptions','duty-list':'Duty List','days-off':'Days Off Manager',settings:'Lists & Settings'}[p];document.querySelector('aside').classList.remove('open');render()}
function dashboardView(){
  const today=isoDay(new Date()),todayDate=new Date(today+'T12:00:00'),end30=addDays(today,30),dateFormat=new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short'}),longDate=new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'2-digit',month:'long'});
  const config={before:+state.settings.leave_days_before||0,after:+state.settings.leave_days_after||0,som:+state.settings.mission_start_days||0,eom:+state.settings.mission_end_days||0};
  const active=state.people.filter(p=>(!p.arrival_date||p.arrival_date<=today)&&(!p.departure_date||p.departure_date>=today)),available=active.filter(p=>dutyAvailability(p,todayDate,config).available),unavailable=active.length-available.length;
  const monday=addDays(today,-((todayDate.getDay()+6)%7)),weekDates=Array.from({length:7},(_,i)=>addDays(monday,i)),weekEnd=weekDates[6],dayOffMap=new Map(state.days_off.map(d=>[d.day_date,d]));
  const personName=id=>{const p=state.people.find(x=>x.id===id);return p?`${p.rank} ${p.last_name} ${p.first_name}`:'Not assigned'};
  const week=weekDates.map(iso=>{const d=new Date(iso+'T12:00:00'),assignment=state.duty_assignments.find(a=>a.day_date===iso),person=assignment&&state.people.find(p=>p.id===assignment.person_id),availability=person?dutyAvailability(person,d,config):null,dayOff=dayOffMap.get(iso),special=d.getDay()===0||dayOff;return {iso,d,assignment,person,availability,dayOff,special,validated:state.validated_days.includes(iso)}});
  const covered=week.filter(x=>x.assignment).length,validated=week.filter(x=>x.validated).length,changes=(state.duty_changes||[]).filter(c=>(c.duty_date>=today&&c.duty_date<=end30)||(c.return_date>=today&&c.return_date<=end30));
  const alerts=[];
  state.days_off.filter(d=>d.day_date>=today&&d.day_date<=end30).forEach(d=>alerts.push({date:d.day_date,type:'Day off',title:d.name,detail:d.observations||'Official non-working day',tone:'red'}));
  state.people.filter(p=>p.arrival_date>today&&p.arrival_date<=end30).forEach(p=>alerts.push({date:p.arrival_date,type:'Arrival',title:`${p.rank} ${p.last_name} ${p.first_name}`,detail:'Mission arrival',tone:'blue'}));
  state.people.filter(p=>p.departure_date>=today&&p.departure_date<=end30).forEach(p=>alerts.push({date:p.departure_date,type:'Departure',title:`${p.rank} ${p.last_name} ${p.first_name}`,detail:'Mission departure',tone:'amber'}));
  state.exemptions.filter(e=>e.end_date>=today&&e.start_date<=end30).forEach(e=>{const p=state.people.find(x=>x.id===e.person_id),ongoing=e.start_date<=today;alerts.push({date:ongoing?today:e.start_date,type:e.reason,title:p?`${p.rank} ${p.last_name} ${p.first_name}`:e.person_name,detail:ongoing?`In progress until ${dateFormat.format(new Date(e.end_date+'T12:00:00'))}`:`${dateFormat.format(new Date(e.start_date+'T12:00:00'))} - ${dateFormat.format(new Date(e.end_date+'T12:00:00'))}`,tone:e.reason==='Holidays'?'yellow':'purple'})});
  changes.forEach(c=>{const next=c.duty_date>=today?c.duty_date:c.return_date;alerts.push({date:next,type:'Duty change',title:`${c.replacement_rank} ${c.replacement_last_name} ${c.replacement_first_name}`,detail:`Initial duty ${dateFormat.format(new Date(c.duty_date+'T12:00:00'))} - return ${dateFormat.format(new Date(c.return_date+'T12:00:00'))}`,tone:'green'})});
  alerts.sort((a,b)=>a.date.localeCompare(b.date)||a.type.localeCompare(b.type));
  const weekRows=week.map(item=>{const type=item.dayOff?item.dayOff.name:item.special?'Sunday / Day off':item.d.getDay()===6?'Saturday':'Regular duty',warning=item.person&&item.availability&&!item.availability.available;return `<div class="week-duty-row ${item.iso===today?'is-today':''} ${item.validated?'is-validated':''} ${!item.assignment?'is-missing':''}"><div class="week-duty-date"><b>${item.d.toLocaleDateString('en-GB',{weekday:'short'}).toUpperCase()}</b><span>${dateFormat.format(item.d)}</span></div><div class="week-duty-person"><strong>${esc(personName(item.assignment?.person_id))}</strong><small>${esc(type)}</small></div><div class="week-duty-status ${warning?'warning':''}">${!item.assignment?'Missing':warning?'Unavailable':item.validated?'Validated':'Forecast'}</div></div>`}).join('');
  const alertRows=alerts.slice(0,6).map(item=>`<div class="outlook-row"><div class="outlook-date"><b>${dateFormat.format(new Date(item.date+'T12:00:00'))}</b><span>${new Date(item.date+'T12:00:00').toLocaleDateString('en-GB',{weekday:'short'})}</span></div><i class="outlook-dot ${item.tone}"></i><div class="outlook-copy"><small>${esc(item.type)}</small><strong>${esc(item.title)}</strong><span>${esc(item.detail)}</span></div></div>`).join('');
  return `<div class="dashboard-command"><section class="dashboard-brief"><div><span class="eyebrow">SCHEDULER OVERVIEW</span><h2>${longDate.format(todayDate)}</h2><p>Current duty readiness and the events that may affect the roster.</p></div><button class="btn primary" onclick="setPage('duty-list')">Open Duty List</button></section><section class="scheduler-kpis"><article><span class="kpi-icon available">✓</span><div><small>Available today</small><strong>${available.length}<em> / ${active.length}</em></strong><p>Active personnel ready for duty</p></div></article><article><span class="kpi-icon unavailable">!</span><div><small>Unavailable today</small><strong>${unavailable}</strong><p>Exemptions and mission buffers</p></div></article><article><span class="kpi-icon coverage">${covered}</span><div><small>Week coverage</small><strong>${covered}<em> / 7 days</em></strong><p>${covered===7?'Current week fully assigned':`${7-covered} service${7-covered===1?'':'s'} still missing`}</p></div></article><article><span class="kpi-icon validation">${validated}</span><div><small>Validated this week</small><strong>${validated}<em> / 7 days</em></strong><p>${changes.length} duty change${changes.length===1?'':'s'} in the next 30 days</p></div></article></section><section class="scheduler-grid"><div class="dashboard-panel week-panel"><div class="dashboard-panel-head"><div><span class="eyebrow">CURRENT WEEK</span><h3>${dateFormat.format(new Date(monday+'T12:00:00'))} - ${dateFormat.format(new Date(weekEnd+'T12:00:00'))}</h3></div><span class="coverage-pill ${covered===7?'complete':''}">${covered}/7 assigned</span></div><div class="week-duty-list">${weekRows}</div></div><div class="dashboard-panel outlook-panel"><div class="dashboard-panel-head"><div><span class="eyebrow">NEXT 30 DAYS</span><h3>Operational outlook</h3></div><span class="outlook-count">${alerts.length} event${alerts.length===1?'':'s'}</span></div><div class="outlook-list">${alertRows||'<div class="dashboard-empty"><b>No operational events</b><span>No arrivals, departures, exemptions or days off in the next 30 days.</span></div>'}</div>${alerts.length>6?`<div class="more-events">+ ${alerts.length-6} additional events</div>`:''}</div></section></div>`;
}
const initials=p=>(p.first_name[0]+p.last_name[0]).toUpperCase();
function visiblePeople(){let today=new Date().toISOString().slice(0,10);if(!showAllPersonnel)return state.people.filter(p=>!p.departure_date||p.departure_date>=today);return [...state.people].sort((a,b)=>(b.departure_date||'0000-00-00').localeCompare(a.departure_date||'0000-00-00'))}
function peopleTable(limit){let a=visiblePeople();if(limit)a=a.slice(0,limit);if(!a.length)return '<div class="empty">No personnel match this view.</div>';return `<div class="table-wrap"><table><thead><tr><th>PERSONNEL</th><th>NATIONALITY</th><th>RANK / DATE OF RANK</th><th>POSITION</th><th>MISSION DATES</th><th></th></tr></thead><tbody>${a.map(p=>`<tr><td><div class="person"><span class="avatar">${initials(p)}</span><div><b>${esc(p.first_name)} ${esc(p.last_name)}</b><br><small>${esc(p.function_number)||'—'}</small></div></div></td><td>${p.nationality_code&&p.nationality_code!=='XX'?`<img class="flag" src="${flagSrc(p.nationality_code)}">`:''}${esc(p.nationality)}</td><td><span class="badge">${esc(p.rank)}</span><br><small>${p.date_of_rank||'—'}</small></td><td>${esc(p.role)||'—'}</td><td><small>${p.arrival_date||'—'} → ${p.departure_date||'—'}</small></td><td><div class="actions"><button class="exemption-action" onclick="exemptionForm(null,${p.id})">Duty Exemption</button><button onclick="personForm(${p.id})">Edit</button><button onclick="remove('people',${p.id})">×</button></div></td></tr>`).join('')}</tbody></table></div>`}
function toggleAllPersonnel(){showAllPersonnel=!showAllPersonnel;render()}
function render(){let c=$('#content');if(page==='dashboard')c.innerHTML=dashboardView();
else if(page==='people')c.innerHTML=`<div class="card panel"><div class="panel-head"><div><h2>Personnel directory <span class="count-badge">${visiblePeople().length}</span></h2><small>${showAllPersonnel?'All personnel · ordered by departure date, newest first':'Current and incoming personnel'}</small></div><div style="display:flex;gap:9px"><button class="btn ghost" onclick="toggleAllPersonnel()">${showAllPersonnel?'Show current':'Show all'}</button><button class="btn primary" onclick="personForm()">＋ Add person</button></div></div>${peopleTable()}</div>`;
else if(page==='exemptions')c.innerHTML=`<div class="card panel"><div class="panel-head"><div><h2>Duty exemptions</h2><small>Periods when personnel cannot be assigned to duty</small></div><button class="btn primary" onclick="exemptionForm()">＋ Add exemption</button></div>${exemptionsTable()}</div>`;
else if(page==='duty-list'){
  c.innerHTML=dutyListView();
  const allDays=state.settings.duty_list_mode!=='two_lists',subtitle=c.querySelector('.duty-toolbar > div:first-child small');
  if(subtitle)subtitle.textContent=`${state.people.length} personnel · ${allDays?'one continuous all-days rotation':'independent regular and Sunday/day-off rotations'}`;
  const nav=c.querySelector('.month-nav'),buttons=[...nav.querySelectorAll('button')];
  const changes=buttons.find(button=>button.textContent.trim()==='Changes');
  const rules=buttons.find(button=>button.textContent.trim()==='Rules of Duty List');
  const clean=buttons.find(button=>button.textContent.trim()==='Clean forecast');
  const current=buttons.find(button=>button.textContent.trim()==='Current month');
  if(changes)changes.classList.add('changes-button');
  if(rules)rules.classList.add('duty-rules-button');
  if(clean&&rules){const full=document.createElement('button');full.type='button';full.className='btn ghost full-export-button';full.textContent='Full Export';full.onclick=exportFullCalendar;clean.after(full);full.after(rules)}
  if(current)current.remove();
  [...nav.querySelectorAll('button')].filter(button=>['‹','›'].includes(button.textContent.trim())).forEach((button,index)=>{button.classList.add('month-arrow',index?'month-next':'month-previous');button.title=index?'Next month':'Previous month';button.setAttribute('aria-label',button.title)});
}
else if(page==='days-off')c.innerHTML=`<div class="card panel"><div class="panel-head"><div><h2>Days off</h2><small>Public holidays and non-working days, newest first</small></div><button class="btn primary" onclick="dayOffForm()">＋ Add day off</button></div>${daysOffTable()}</div>`;
else {
  c.innerHTML=settings();
  const form=c.querySelector('#service-settings-form');
  if(form)form.insertAdjacentHTML('afterbegin',`<div class="field full duty-mode-field"><label>Duty list mode</label><select name="duty_list_mode" required><option value="all_days" ${state.settings.duty_list_mode!=='two_lists'?'selected':''}>Duty List - All days</option><option value="two_lists" ${state.settings.duty_list_mode==='two_lists'?'selected':''}>Duty List - 2 List - Normal and Day Off</option></select><small>${state.settings.duty_list_mode==='two_lists'?'Regular days and Sundays/days off use independent rotations.':'Every calendar day follows one continuous rotation.'}</small></div>`);
}}
function exemptionsTable(){if(!state.exemptions.length)return '<div class="empty">No duty exemptions recorded.</div>';return `<div class="table-wrap"><table><thead><tr><th>PERSONNEL</th><th>REASON</th><th>PERIOD</th><th>OBSERVATIONS</th><th></th></tr></thead><tbody>${state.exemptions.map(e=>`<tr><td><b>${esc(e.person_name)}</b></td><td><span class="badge leave">${esc(e.reason)}</span></td><td>${e.start_date} → ${e.end_date}</td><td>${esc(e.observations)||'—'}</td><td><div class="actions"><button onclick="exemptionForm(${e.id})">Edit</button><button onclick="remove('exemptions',${e.id})">×</button></div></td></tr>`).join('')}</tbody></table></div>`}
function daysOffTable(){if(!state.days_off.length)return '<div class="empty">No days off recorded.</div>';return `<div class="table-wrap"><table><thead><tr><th>DATE</th><th>NAME</th><th>OBSERVATIONS</th><th></th></tr></thead><tbody>${state.days_off.map(d=>`<tr><td><span class="badge">${d.day_date}</span></td><td><b>${esc(d.name)}</b></td><td>${esc(d.observations)||'—'}</td><td><div class="actions"><button onclick="dayOffForm(${d.id})">Edit</button><button onclick="remove('days-off',${d.id})">×</button></div></td></tr>`).join('')}</tbody></table></div>`}
function settings(){let list=(type,items)=>`<div class="card panel"><div class="panel-head"><h2>${type==='nationalities'?'Nationalities':'Ranks'}</h2><button class="btn ghost" onclick="listForm('${type}')">＋ Add</button></div>${items.map(x=>`<div class="list-row"><span>${type==='nationalities'&&x.code&&x.code!=='XX'?`<img class="flag" src="${flagSrc(x.code)}">`:''}<b>${esc(x.name)}</b>${type==='nationalities'?` <small>${esc(x.code)}</small>`:''}</span><span class="actions"><button onclick="listForm('${type}',${x.id})">Edit</button><button onclick="remove('${type}',${x.id})">×</button></span></div>`).join('')}</div>`;return `<div class="card panel" style="margin-top:0;margin-bottom:20px"><div class="panel-head"><div><h2>Chief of Staff (COS)</h2><small>Identification used in duty roster documents</small></div></div><form class="form" id="cos-form" style="padding:0"><div class="field"><label>Name</label><input name="cos_name" value="${esc(state.settings.cos_name)}" placeholder="Chief of Staff name"></div><div class="field"><label>Rank</label><input name="cos_rank" value="${esc(state.settings.cos_rank)}" placeholder="e.g. OF-4"></div><div class="form-actions"><button class="btn primary">Save COS details</button></div></form></div><div class="card panel" style="margin-top:0;margin-bottom:20px"><div class="panel-head"><div><h2>Duty Service Settings</h2><small>Automatic duty exemption periods</small></div></div><form class="form" id="service-settings-form" style="padding:0"><div class="field"><label>Exemption days before leave (holidays)</label><input type="number" min="0" step="1" name="leave_days_before" value="${esc(state.settings.leave_days_before??3)}" required></div><div class="field"><label>Exemption days after leave (holidays)</label><input type="number" min="0" step="1" name="leave_days_after" value="${esc(state.settings.leave_days_after??3)}" required></div><div class="field"><label>Mission start exemption days (SOM)</label><input type="number" min="0" step="1" name="mission_start_days" value="${esc(state.settings.mission_start_days??7)}" required></div><div class="field"><label>Mission end exemption days (EOM)</label><input type="number" min="0" step="1" name="mission_end_days" value="${esc(state.settings.mission_end_days??15)}" required></div><div class="form-actions"><button class="btn primary">Save duty settings</button></div></form></div><div class="card panel backup-panel"><div class="panel-head"><div><h2>Standalone data</h2><small>Portable JSON backup and restore</small></div><div class="backup-actions"><button class="btn ghost" onclick="exportDatabase()">Export backup</button><button class="btn ghost" onclick="importDatabase()">Import backup</button><button class="btn danger" onclick="resetDatabase()">Restore original</button></div></div></div><div class="settings-grid">${list('nationalities',state.nationalities)}${list('ranks',state.ranks)}</div>`}
function modal(title,html,onSave){$('#modal').innerHTML=`<div class="dialog"><div class="dialog-head"><h2>${title}</h2><button class="close" onclick="closeModal()">×</button></div><form class="form" id="form">${html}<div class="form-actions"><button type="button" class="btn ghost" onclick="closeModal()">Cancel</button><button class="btn primary">Save changes</button></div></form></div>`;$('#modal').classList.add('open');$('#form').onsubmit=async e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target));try{await onSave(d);closeModal();await load();toast('Saved successfully')}catch(x){toast(x.message)}}}
function closeModal(){$('#modal').classList.remove('open')};const field=(label,name,type='text',value='',full=false,required=true)=>`<div class="field ${full?'full':''}"><label>${label}</label><input name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''}></div>`;
function personForm(id){let p=state.people.find(x=>x.id===id)||{};modal(id?'Edit personnel':'Add personnel',`<div class="form-row-three"><div class="field"><label>Nationality</label><select name="nationality_id" required>${state.nationalities.map(x=>`<option value="${x.id}" ${x.id==p.nationality_id?'selected':''}>${esc(x.name)}</option>`)}</select></div><div class="field"><label>Rank</label><select name="rank_id" required>${state.ranks.map(x=>`<option value="${x.id}" ${x.id==p.rank_id?'selected':''}>${esc(x.name)}</option>`)}</select></div><div class="field"><label>Date of Rank</label><input name="date_of_rank" type="date" value="${esc(p.date_of_rank||'')}"></div></div>${field('First name','first_name','text',p.first_name)}${field('Last name','last_name','text',p.last_name)}${field('Position number','function_number','text',p.function_number,false,false)}${field('Position','role','text',p.role,false,false)}${field('Arrival date','arrival_date','date',p.arrival_date)}${field('Departure date','departure_date','date',p.departure_date)}`,d=>api('/api/people'+(id?'/'+id:''),{method:id?'PUT':'POST',body:d}))}
function exemptionForm(id,personId){if(!state.people.length)return toast('Add personnel before creating an exemption');let e=state.exemptions.find(x=>x.id===id)||{};let selectedPerson=e.person_id||personId;modal(id?'Edit exemption':'Add duty exemption',`<div class="field full"><label>Personnel</label><select name="person_id" required>${state.people.map(x=>`<option value="${x.id}" ${x.id==selectedPerson?'selected':''}>${esc(x.first_name+' '+x.last_name)}</option>`)}</select></div><div class="field"><label>Reason</label><select name="reason"><option ${e.reason==='Holidays'?'selected':''}>Holidays</option><option ${e.reason==='Other'?'selected':''}>Other</option></select></div><div></div>${field('Start date','start_date','date',e.start_date)}${field('End date','end_date','date',e.end_date)}<div class="field full"><label>Observations</label><textarea name="observations" rows="4">${esc(e.observations)}</textarea></div>`,d=>api('/api/exemptions'+(id?'/'+id:''),{method:id?'PUT':'POST',body:d}))}
function dayOffForm(id){let d=state.days_off.find(x=>x.id===id)||{};modal(id?'Edit day off':'Add day off',`${field('Name','name','text',d.name,true)}${field('Date','day_date','date',d.day_date)}<div></div><div class="field full"><label>Observations</label><textarea name="observations" rows="4">${esc(d.observations)}</textarea></div>`,x=>api('/api/days-off'+(id?'/'+id:''),{method:id?'PUT':'POST',body:x}))}
function listForm(type,id){let x=state[type].find(v=>v.id===id)||{};modal(`${id?'Edit':'Add'} ${type==='ranks'?'rank':'nationality'}`,field(type==='ranks'?'Rank name':'Country name','name','text',x.name,true)+(type==='nationalities'?field('Country code (e.g. PT)','code','text',x.code,true,false):''),d=>api('/api/'+type+(id?'/'+id:''),{method:id?'PUT':'POST',body:d}))}
async function remove(type,id){if(!confirm('Delete this record?'))return;try{await api('/api/'+type+'/'+id,{method:'DELETE'});await load();toast('Record deleted')}catch(e){toast(e.message)}}
document.querySelectorAll('button.nav[data-page]').forEach(x=>x.onclick=()=>setPage(x.dataset.page));$('#menu').onclick=()=>document.querySelector('aside').classList.toggle('open');$('#today').textContent=new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric'}).format(new Date());document.addEventListener('submit',async e=>{if(!['cos-form','service-settings-form'].includes(e.target.id))return;e.preventDefault();try{await api('/api/settings',{method:'PUT',body:Object.fromEntries(new FormData(e.target))});await load();toast(e.target.id==='cos-form'?'COS details saved':'Duty settings saved')}catch(x){toast(x.message)}});load();
