(() => {
  'use strict';
  const STORE='dlh.standalone.database.v3',BACKUPS='dlh.standalone.backups.v3';
  const clone=value=>JSON.parse(JSON.stringify(value));
  let db=(()=>{try{return JSON.parse(localStorage.getItem(STORE))||clone(window.DLH_SEED)}catch{return clone(window.DLH_SEED)}})();
  const save=()=>localStorage.setItem(STORE,JSON.stringify(db));
  const nextId=list=>Math.max(0,...list.map(x=>Number(x.id)||0))+1;
  const pad=n=>String(n).padStart(2,'0');
  const parse=s=>{const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d,12)};
  const iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
  const add=(s,n)=>{const d=typeof s==='string'?parse(s):new Date(s);d.setDate(d.getDate()+n);return iso(d)};
  const dayOff=s=>parse(s).getDay()===0||db.days_off.some(x=>x.day_date===s);
  const rotation=s=>db.settings.duty_list_mode==='two_lists'?(dayOff(s)?'special':'regular'):'all';
  const rankKey=p=>{const [g,n]=String(p.rank||rank(p.rank_id)?.name||'').split('-');return[p.arrival_date||'9999-12-31',{OR:0,WO:1,OF:2}[g]??3,Number(n)||0,p.date_of_rank||'9999-12-31',p.last_name||'',p.first_name||'',p.id]};
  const compareKey=(a,b)=>{for(let i=0;i<a.length;i++)if(a[i]!==b[i])return typeof a[i]==='number'?a[i]-b[i]:String(a[i]).localeCompare(String(b[i]),'en');return 0};
  const rank=id=>db.ranks.find(x=>x.id===Number(id));
  const nationality=id=>db.nationalities.find(x=>x.id===Number(id));
  const person=id=>db.people.find(x=>x.id===Number(id));
  const available=(p,s)=>{if(p.arrival_date&&s<p.arrival_date)return false;if(p.departure_date&&s>p.departure_date)return false;const som=Math.max(0,+db.settings.mission_start_days||0),eom=Math.max(0,+db.settings.mission_end_days||0);if(som&&p.arrival_date&&s>=p.arrival_date&&s<=add(p.arrival_date,som-1))return false;if(eom&&p.departure_date&&s>=add(p.departure_date,-eom+1)&&s<=p.departure_date)return false;const before=Math.max(0,+db.settings.leave_days_before||0),after=Math.max(0,+db.settings.leave_days_after||0);return !db.exemptions.some(e=>e.person_id===p.id&&s>=add(e.start_date,e.reason==='Holidays'?-before:0)&&s<=add(e.end_date,e.reason==='Holidays'?after:0))};
  const enrichPerson=p=>({...p,nationality:nationality(p.nationality_id)?.name||'',nationality_code:nationality(p.nationality_id)?.code||'XX',rank:rank(p.rank_id)?.name||''});
  const enrichChange=c=>{const o=enrichPerson(person(c.original_person_id)||{}),r=enrichPerson(person(c.replacement_person_id)||{});return {...c,original_first_name:o.first_name||'',original_last_name:o.last_name||'',original_rank:o.rank||'',replacement_first_name:r.first_name||'',replacement_last_name:r.last_name||'',replacement_rank:r.rank||''}};
  function bootstrap(){const people=db.people.map(enrichPerson).sort((a,b)=>compareKey(rankKey(a),rankKey(b)));const exemptions=db.exemptions.map(e=>({...e,person_name:person(e.person_id)?`${person(e.person_id).first_name} ${person(e.person_id).last_name}`:''})).sort((a,b)=>b.start_date.localeCompare(a.start_date));return {nationalities:[...db.nationalities].sort((a,b)=>a.name.localeCompare(b.name)),ranks:[...db.ranks].sort((a,b)=>compareKey(rankKey({rank:a.name,id:a.id}),rankKey({rank:b.name,id:b.id}))),people,exemptions,days_off:[...db.days_off].sort((a,b)=>b.day_date.localeCompare(a.day_date)||b.id-a.id),duty_assignments:[...db.duty_assignments].sort((a,b)=>a.day_date.localeCompare(b.day_date)),duty_changes:db.duty_changes.map(enrichChange).sort((a,b)=>a.duty_date.localeCompare(b.duty_date)),validated_days:[...db.validated_days].sort(),settings:{...db.settings},stats:{personnel:people.length,exemptions:exemptions.length}}}
  function forecast(start,end){const fixed=new Map(db.duty_assignments.filter(a=>a.day_date<start||db.validated_days.includes(a.day_date)||a.source==='manual').map(a=>[a.day_date,a]));db.duty_assignments=db.duty_assignments.filter(a=>!(a.day_date>=start&&a.day_date<=end&&a.source==='forecast'&&!db.validated_days.includes(a.day_date)));const last={all:new Map(),regular:new Map(),special:new Map()};let previous=null;[...fixed.values()].sort((a,b)=>a.day_date.localeCompare(b.day_date)).forEach(a=>{if(a.day_date<start){last[rotation(a.day_date)].set(a.person_id,a.day_date);if(a.day_date===add(start,-1))previous=a.person_id}});const candidates=(s,r,excluded=new Set())=>db.people.filter(p=>!excluded.has(p.id)&&available(p,s)).sort((a,b)=>{const al=last[r].get(a.id),bl=last[r].get(b.id);if(Boolean(al)!==Boolean(bl))return al?1:-1;if(al!==bl)return String(al||'').localeCompare(String(bl||''));return compareKey(rankKey(enrichPerson(a)),rankKey(enrichPerson(b)))});let generated=0;for(let current=start;current<=end;current=add(current,1)){const r=rotation(current),existing=db.duty_assignments.find(a=>a.day_date===current);if(existing){last[r].set(existing.person_id,current);previous=existing.person_id;continue}const excluded=new Set(previous?[previous]:[]),tomorrow=add(current,1);if(db.settings.duty_list_mode==='two_lists'&&r==='regular'&&dayOff(tomorrow)){const fixedTomorrow=db.duty_assignments.find(a=>a.day_date===tomorrow);if(fixedTomorrow)excluded.add(fixedTomorrow.person_id);else{const special=candidates(tomorrow,'special');if(special[0])excluded.add(special[0].id)}}const chosen=candidates(current,r,excluded)[0];if(chosen){db.duty_assignments.push({id:nextId(db.duty_assignments),day_date:current,person_id:chosen.id,source:'forecast',updated_at:new Date().toISOString()});last[r].set(chosen.id,current);previous=chosen.id;generated++}else previous=null}save();return generated}
  function createChange(body){const s=body.duty_date,replacement=Number(body.replacement_person_id);if(!db.validated_days.includes(s))throw Error('Only a validated duty service can be changed.');const duty=db.duty_assignments.find(a=>a.day_date===s);if(!duty)throw Error('There is no duty officer assigned on the selected day.');if(duty.person_id===replacement)throw Error('Select a different duty officer.');if(db.duty_changes.some(c=>[c.duty_date,c.return_date].includes(s)))throw Error('The selected duty is already part of a change.');const replacementPerson=person(replacement);if(!replacementPerson||!available(replacementPerson,s))throw Error('The replacement is not available on the selected day.');const r=rotation(s),used=new Set(db.duty_changes.flatMap(c=>[c.duty_date,c.return_date]));const returnDuty=db.duty_assignments.filter(a=>a.person_id===replacement&&a.day_date>s&&rotation(a.day_date)===r&&!used.has(a.day_date)).sort((a,b)=>a.day_date.localeCompare(b.day_date))[0];if(!returnDuty)throw Error('That person has no future duty of the same type available for the return change.');const c={id:nextId(db.duty_changes),duty_date:s,original_person_id:duty.person_id,replacement_person_id:replacement,return_date:returnDuty.day_date,original_source:duty.source,return_source:returnDuty.source,created_at:new Date().toISOString()};duty.person_id=replacement;duty.source='manual';returnDuty.person_id=c.original_person_id;returnDuty.source='manual';db.duty_changes.push(c);save();return c}
  function deleteChange(id){const c=db.duty_changes.find(x=>x.id===Number(id));if(!c)throw Error('Duty change not found.');const a=db.duty_assignments.find(x=>x.day_date===c.duty_date),b=db.duty_assignments.find(x=>x.day_date===c.return_date);if(a){a.person_id=c.original_person_id;a.source=c.original_source}if(b){b.person_id=c.replacement_person_id;b.source=c.return_source}db.duty_changes=db.duty_changes.filter(x=>x.id!==c.id);save()}
  const json=(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json'}});
  const file=(bytes,name,type)=>new Response(bytes,{status:200,headers:{'Content-Type':type,'Content-Disposition':`attachment; filename="${name}"`}});
  const body=opt=>{try{return typeof opt.body==='string'?JSON.parse(opt.body):opt.body||{}}catch{return {}}};
  function crud(resource,id,method,data){const map={people:'people',nationalities:'nationalities',ranks:'ranks',exemptions:'exemptions','days-off':'days_off'},key=map[resource],list=db[key];if(method==='DELETE'){const n=Number(id);if(resource==='people'&&(db.exemptions.some(e=>e.person_id===n)||db.duty_assignments.some(a=>a.person_id===n)))throw Error('This personnel record is referenced by duty data.');db[key]=list.filter(x=>x.id!==n);save();return {ok:true}}if(resource==='people'){data={...data,nationality_id:Number(data.nationality_id),rank_id:Number(data.rank_id),first_name:String(data.first_name||'').toUpperCase(),last_name:String(data.last_name||'').toUpperCase()}}if(resource==='exemptions')data={...data,person_id:Number(data.person_id)};if(data.start_date&&data.end_date&&data.start_date>data.end_date)throw Error('End date must be on or after start date.');if(method==='POST'){const row={id:nextId(list),...data};list.push(row);save();return {id:row.id}}const row=list.find(x=>x.id===Number(id));if(!row)throw Error('Record not found.');Object.assign(row,data);save();return {ok:true}}
  async function handle(url,opt={}){const path=String(url).replace(/^https?:\/\/[^/]+/,'').split('?')[0],method=(opt.method||'GET').toUpperCase(),data=body(opt);try{
    const write=method!=='GET'&&!['/api/heartbeat','/api/client-closing','/api/duty-calendar-export','/api/duty-list-export'].includes(path);
    if(write&&sessionStorage.getItem('dlh.admin.unlocked')!=='1')throw Error('Editing is protected. Unlock with the administration code first.');
    if(path==='/api/bootstrap')return json(bootstrap());
    if(path==='/api/heartbeat'||path==='/api/client-closing')return json({ok:true});
    if(path==='/api/settings'&&method==='PUT'){Object.assign(db.settings,data);save();return json({ok:true})}
    if(path==='/api/duty-forecast'&&method==='POST')return json({generated:forecast(data.start_date,data.end_date)});
    if(path==='/api/duty-forecast-clean'&&method==='POST'){const last=[...db.validated_days].sort().at(-1)||'';const before=db.duty_assignments.length;db.duty_assignments=db.duty_assignments.filter(a=>a.source!=='forecast'||(last&&a.day_date<=last));save();return json({removed:before-db.duty_assignments.length})}
    if(path==='/api/duty-manual'&&method==='POST'){for(const c of data.changes||[]){if(db.validated_days.includes(c.day_date))throw Error('Unvalidate the day before changing its duty service.');db.duty_assignments=db.duty_assignments.filter(a=>a.day_date!==c.day_date);if(c.person_id!=null)db.duty_assignments.push({id:nextId(db.duty_assignments),day_date:c.day_date,person_id:Number(c.person_id),source:'manual',updated_at:new Date().toISOString()})}save();return json({ok:true})}
    if(path==='/api/validated-days'&&method==='POST'){db.validated_days=db.validated_days.filter(x=>x!==data.day_date);if(data.validated)db.validated_days.push(data.day_date);save();return json({ok:true})}
    if(path==='/api/duty-changes'&&method==='POST'){const c=createChange(data);return json({ok:true,return_date:c.return_date},201)}
    const changeMatch=path.match(/^\/api\/duty-changes\/(\d+)$/);if(changeMatch&&method==='DELETE'){deleteChange(changeMatch[1]);return json({ok:true})}
    if(path==='/api/duty-list-export'&&method==='POST'){const result=await window.DLH_EXPORTS.week(data,bootstrap());return file(result.bytes,result.name,'application/vnd.openxmlformats-officedocument.wordprocessingml.document')}
    if(path==='/api/duty-calendar-export'&&method==='POST'){const result=await window.DLH_EXPORTS.calendar(data.start_date,bootstrap());return file(result.bytes,result.name,'application/pdf')}
    if(path==='/api/duty-rules-export'){const result=await window.DLH_EXPORTS.rules(bootstrap());return file(result.bytes,result.name,'application/vnd.openxmlformats-officedocument.wordprocessingml.document')}
    const match=path.match(/^\/api\/([^/]+)(?:\/(\d+))?$/);if(match&&['people','nationalities','ranks','exemptions','days-off'].includes(match[1]))return json(crud(match[1],match[2],method,data),method==='POST'?201:200);
    return json({error:'Not found'},404);
  }catch(error){return json({error:error.message||'Something went wrong'},400)}}
  const originalFetch=window.fetch?.bind(window);window.fetch=(url,opt)=>String(url).startsWith('/api/')?handle(url,opt):originalFetch(url,opt);
  window.DLH_DB={export(){return clone(db)},import(value){db=clone(value);save()},reset(){db=clone(window.DLH_SEED);save()},backups(){return JSON.parse(localStorage.getItem(BACKUPS)||'[]')}};
  try{const list=window.DLH_DB.backups();list.unshift({created:new Date().toISOString(),data:clone(db)});localStorage.setItem(BACKUPS,JSON.stringify(list.slice(0,10)))}catch{}
})();
